### ISSUE TITLE
dyld loading error on MacOS 10.13.6

### ISSUE THREAD

**Issue by betamos** [betamos/payload#2]
A user reported a dyld load time error, preventing Payload from starting. See stack trace here: https://github.com/tauri-apps/tauri/issues/4387

It was root-caused to mac-notification-sys, which is a Tauri dep: https://github.com/h4llow3En/mac-notification-sys/issues/45

This issue will be fixed in the next version of Payload.

However, 10.13.* is still struggling with a separate whitescreen issue.

**Comment by abu0306** [comment]
Hi, i have the same erro, did you modify it like this?
`
    "allowlist": {
      "all": true,
      "notification": {
        "all": false
      }
    },
`

**Comment by betamos** [comment]
You can just remove the notification block entirely, and yes that should work but then you don't have any notifications. I built with the PR in the linked issue, which works too.

**Comment by betamos** [comment]
This should be fixed at this point.
